"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/theme-provider"

interface Language {
  code: string
  name: string
  direction: "ltr" | "rtl"
}

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const languages: Language[] = [
  { code: "ar", name: "العربية", direction: "rtl" },
  { code: "en", name: "English", direction: "ltr" },
]

const translations = {
  ar: {
    home: "الرئيسية",
    products: "المنتجات",
    categories: "الفئات",
    cart: "السلة",
    search: "البحث",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    profile: "الملف الشخصي",
    orders: "الطلبات",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    addToCart: "أضف إلى السلة",
    buyNow: "اشتري الآن",
    price: "السعر",
    description: "الوصف",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    trackOrder: "تتبع الطلب",
    orderCode: "رمز الطلب",
    customerName: "اسم العميل",
    customerEmail: "البريد الإلكتروني",
    customerPhone: "رقم الهاتف",
    customerAddress: "العنوان",
    orderStatus: "حالة الطلب",
    paymentStatus: "حالة الدفع",
    pending: "في الانتظار",
    processing: "قيد المعالجة",
    shipped: "تم الشحن",
    delivered: "تم التسليم",
    cancelled: "ملغي",
    paid: "مدفوع",
    failed: "فشل",
    cash: "نقدي",
    card: "بطاقة",
    admin: "الإدارة",
    dashboard: "لوحة التحكم",
    manageProducts: "إدارة المنتجات",
    manageCategories: "إدارة الفئات",
    manageOrders: "إدارة الطلبات",
    addProduct: "إضافة منتج",
    editProduct: "تعديل منتج",
    deleteProduct: "حذف منتج",
    addCategory: "إضافة فئة",
    editCategory: "تعديل فئة",
    deleteCategory: "حذف فئة",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    view: "عرض",
    name: "الاسم",
    image: "الصورة",
    category: "الفئة",
    createdAt: "تاريخ الإنشاء",
    updatedAt: "تاريخ التحديث",
    actions: "الإجراءات",
    noData: "لا توجد بيانات",
    loading: "جاري التحميل...",
    error: "خطأ",
    success: "نجح",
    warning: "تحذير",
    info: "معلومات",
    confirm: "تأكيد",
    yes: "نعم",
    no: "لا",
    close: "إغلاق",
    next: "التالي",
    previous: "السابق",
    first: "الأول",
    last: "الأخير",
    page: "صفحة",
    of: "من",
    total: "المجموع",
    items: "عناصر",
    showing: "عرض",
    to: "إلى",
    results: "نتائج",
    noResults: "لا توجد نتائج",
    searchPlaceholder: "ابحث عن المنتجات...",
    filterBy: "تصفية حسب",
    sortBy: "ترتيب حسب",
    newest: "الأحدث",
    oldest: "الأقدم",
    priceHighToLow: "السعر من الأعلى إلى الأقل",
    priceLowToHigh: "السعر من الأقل إلى الأعلى",
    nameAZ: "الاسم أ-ي",
    nameZA: "الاسم ي-أ",
    all: "الكل",
    featured: "مميز",
    newArrivals: "وصل حديثاً",
    bestSellers: "الأكثر مبيعاً",
    onSale: "في التخفيضات",
    clearFilters: "مسح المرشحات",
    applyFilters: "تطبيق المرشحات",
    showMore: "عرض المزيد",
    showLess: "عرض أقل",
    readMore: "اقرأ المزيد",
    readLess: "اقرأ أقل",
    share: "مشاركة",
    wishlist: "قائمة الأمنيات",
    compare: "مقارنة",
    quickView: "عرض سريع",
    addToWishlist: "أضف إلى قائمة الأمنيات",
    removeFromWishlist: "إزالة من قائمة الأمنيات",
    addToCompare: "أضف للمقارنة",
    removeFromCompare: "إزالة من المقارنة",
    checkout: "الدفع",
    continueShopping: "متابعة التسوق",
    emptyCart: "السلة فارغة",
    cartTotal: "إجمالي السلة",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    shipping: "الشحن",
    discount: "الخصم",
    coupon: "كوبون",
    applyCoupon: "تطبيق الكوبون",
    removeCoupon: "إزالة الكوبون",
    quantity: "الكمية",
    remove: "إزالة",
    update: "تحديث",
    updateCart: "تحديث السلة",
    proceedToCheckout: "متابعة للدفع",
    backToCart: "العودة للسلة",
    orderSummary: "ملخص الطلب",
    billingAddress: "عنوان الفاتورة",
    shippingAddress: "عنوان الشحن",
    paymentMethod: "طريقة الدفع",
    placeOrder: "تأكيد الطلب",
    orderPlaced: "تم تأكيد الطلب",
    orderNumber: "رقم الطلب",
    orderDate: "تاريخ الطلب",
    estimatedDelivery: "التسليم المتوقع",
    trackYourOrder: "تتبع طلبك",
    orderDetails: "تفاصيل الطلب",
    shippingDetails: "تفاصيل الشحن",
    paymentDetails: "تفاصيل الدفع",
    contactUs: "اتصل بنا",
    aboutUs: "من نحن",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    faq: "الأسئلة الشائعة",
    support: "الدعم",
    newsletter: "النشرة الإخبارية",
    subscribe: "اشتراك",
    unsubscribe: "إلغاء الاشتراك",
    followUs: "تابعنا",
    socialMedia: "وسائل التواصل الاجتماعي",
    facebook: "فيسبوك",
    twitter: "تويتر",
    instagram: "إنستغرام",
    youtube: "يوتيوب",
    linkedin: "لينكد إن",
    copyright: "جميع الحقوق محفوظة",
    poweredBy: "مدعوم بواسطة",
    version: "الإصدار",
    language: "اللغة",
    currency: "العملة",
    country: "البلد",
    region: "المنطقة",
    timezone: "المنطقة الزمنية",
    theme: "المظهر",
    lightMode: "المظهر الفاتح",
    darkMode: "المظهر الداكن",
    systemMode: "مظهر النظام",
    notifications: "الإشعارات",
    emailNotifications: "إشعارات البريد الإلكتروني",
    smsNotifications: "إشعارات الرسائل النصية",
    pushNotifications: "الإشعارات المباشرة",
    account: "الحساب",
    personalInfo: "المعلومات الشخصية",
    changePassword: "تغيير كلمة المرور",
    deleteAccount: "حذف الحساب",
    twoFactorAuth: "المصادقة الثنائية",
    loginHistory: "تاريخ تسجيل الدخول",
    connectedAccounts: "الحسابات المتصلة",
    dataExport: "تصدير البيانات",
    dataImport: "استيراد البيانات",
    backup: "نسخ احتياطي",
    restore: "استعادة",
    maintenance: "صيانة",
    systemStatus: "حالة النظام",
    uptime: "وقت التشغيل",
    performance: "الأداء",
    analytics: "التحليلات",
    reports: "التقارير",
    statistics: "الإحصائيات",
    metrics: "المقاييس",
    logs: "السجلات",
    audit: "التدقيق",
    security: "الأمان",
    permissions: "الصلاحيات",
    roles: "الأدوار",
    users: "المستخدمون",
    groups: "المجموعات",
    teams: "الفرق",
    organizations: "المنظمات",
    departments: "الأقسام",
    branches: "الفروع",
    locations: "المواقع",
    warehouses: "المستودعات",
    inventory: "المخزون",
    stock: "المخزون",
    suppliers: "الموردون",
    vendors: "البائعون",
    customers: "العملاء",
    clients: "العملاء",
    partners: "الشركاء",
    affiliates: "الشركاء التابعون",
    resellers: "الموزعون",
    distributors: "الموزعون",
    retailers: "تجار التجزئة",
    wholesalers: "تجار الجملة",
    manufacturers: "المصنعون",
    brands: "العلامات التجارية",
    models: "الموديلات",
    variants: "المتغيرات",
    options: "الخيارات",
    attributes: "الخصائص",
    specifications: "المواصفات",
    features: "الميزات",
    benefits: "الفوائد",
    advantages: "المزايا",
    disadvantages: "العيوب",
    pros: "الإيجابيات",
    cons: "السلبيات",
    reviews: "المراجعات",
    ratings: "التقييمات",
    comments: "التعليقات",
    feedback: "التعليقات",
    testimonials: "الشهادات",
    recommendations: "التوصيات",
    suggestions: "الاقتراحات",
    complaints: "الشكاوى",
    issues: "المشاكل",
    bugs: "الأخطاء",
    fixes: "الإصلاحات",
    updates: "التحديثات",
    upgrades: "الترقيات",
    patches: "التصحيحات",
    releases: "الإصدارات",
    versions: "الإصدارات",
    changelog: "سجل التغييرات",
    roadmap: "خارطة الطريق",
    milestones: "المعالم",
    goals: "الأهداف",
    objectives: "الأهداف",
    targets: "الأهداف",
    kpis: "مؤشرات الأداء الرئيسية",
    metrics: "المقاييس",
    benchmarks: "المعايير المرجعية",
    standards: "المعايير",
    guidelines: "الإرشادات",
    policies: "السياسات",
    procedures: "الإجراءات",
    processes: "العمليات",
    workflows: "سير العمل",
    automation: "الأتمتة",
    integration: "التكامل",
    synchronization: "المزامنة",
    migration: "الترحيل",
    transformation: "التحويل",
    optimization: "التحسين",
    enhancement: "التحسين",
    improvement: "التحسين",
    innovation: "الابتكار",
    development: "التطوير",
    research: "البحث",
    testing: "الاختبار",
    validation: "التحقق",
    verification: "التحقق",
    certification: "الشهادة",
    compliance: "الامتثال",
    governance: "الحوكمة",
    risk: "المخاطر",
    mitigation: "التخفيف",
    prevention: "الوقاية",
    protection: "الحماية",
    safety: "السلامة",
    health: "الصحة",
    environment: "البيئة",
    sustainability: "الاستدامة",
    responsibility: "المسؤولية",
    ethics: "الأخلاق",
    values: "القيم",
    principles: "المبادئ",
    culture: "الثقافة",
    mission: "المهمة",
    vision: "الرؤية",
    strategy: "الاستراتيجية",
    planning: "التخطيط",
    execution: "التنفيذ",
    monitoring: "المراقبة",
    evaluation: "التقييم",
    assessment: "التقييم",
    measurement: "القياس",
    tracking: "التتبع",
    progress: "التقدم",
    status: "الحالة",
    condition: "الحالة",
    state: "الحالة",
    phase: "المرحلة",
    stage: "المرحلة",
    step: "الخطوة",
    level: "المستوى",
    grade: "الدرجة",
    rank: "الرتبة",
    position: "الموضع",
    location: "الموقع",
    address: "العنوان",
    coordinates: "الإحداثيات",
    map: "الخريطة",
    directions: "الاتجاهات",
    navigation: "التنقل",
    route: "المسار",
    path: "المسار",
    journey: "الرحلة",
    trip: "الرحلة",
    travel: "السفر",
    transport: "النقل",
    delivery: "التسليم",
    shipping: "الشحن",
    logistics: "اللوجستيات",
    fulfillment: "التنفيذ",
    processing: "المعالجة",
    handling: "التعامل",
    management: "الإدارة",
    administration: "الإدارة",
    operation: "التشغيل",
    maintenance: "الصيانة",
    service: "الخدمة",
    support: "الدعم",
    assistance: "المساعدة",
    help: "المساعدة",
    guidance: "التوجيه",
    instruction: "التعليمات",
    tutorial: "البرنامج التعليمي",
    guide: "الدليل",
    manual: "الدليل",
    documentation: "التوثيق",
    reference: "المرجع",
    resource: "المورد",
    tool: "الأداة",
    utility: "الأداة المساعدة",
    application: "التطبيق",
    software: "البرمجيات",
    program: "البرنامج",
    system: "النظام",
    platform: "المنصة",
    framework: "الإطار",
    library: "المكتبة",
    module: "الوحدة",
    component: "المكون",
    element: "العنصر",
    item: "العنصر",
    object: "الكائن",
    entity: "الكيان",
    record: "السجل",
    entry: "الإدخال",
    data: "البيانات",
    information: "المعلومات",
    content: "المحتوى",
    material: "المادة",
    resource: "المورد",
    asset: "الأصل",
    property: "الخاصية",
    attribute: "الخاصية",
    field: "الحقل",
    column: "العمود",
    row: "الصف",
    table: "الجدول",
    list: "القائمة",
    array: "المصفوفة",
    collection: "المجموعة",
    set: "المجموعة",
    group: "المجموعة",
    cluster: "العنقود",
    bundle: "الحزمة",
    package: "الحزمة",
    container: "الحاوية",
    wrapper: "الغلاف",
    envelope: "المغلف",
    box: "الصندوق",
    folder: "المجلد",
    directory: "الدليل",
    file: "الملف",
    document: "الوثيقة",
    report: "التقرير",
    summary: "الملخص",
    overview: "نظرة عامة",
    preview: "معاينة",
    sample: "عينة",
    example: "مثال",
    demo: "عرض توضيحي",
    prototype: "النموذج الأولي",
    template: "القالب",
    pattern: "النمط",
    format: "التنسيق",
    structure: "الهيكل",
    layout: "التخطيط",
    design: "التصميم",
    style: "الأسلوب",
    appearance: "المظهر",
    look: "المظهر",
    feel: "الإحساس",
    experience: "التجربة",
    interface: "الواجهة",
    interaction: "التفاعل",
    behavior: "السلوك",
    functionality: "الوظيفة",
    capability: "القدرة",
    capacity: "السعة",
    performance: "الأداء",
    efficiency: "الكفاءة",
    effectiveness: "الفعالية",
    productivity: "الإنتاجية",
    quality: "الجودة",
    reliability: "الموثوقية",
    stability: "الاستقرار",
    consistency: "الاتساق",
    accuracy: "الدقة",
    precision: "الدقة",
    correctness: "الصحة",
    validity: "الصحة",
    integrity: "التكامل",
    completeness: "الاكتمال",
    availability: "التوفر",
    accessibility: "إمكانية الوصول",
    usability: "سهولة الاستخدام",
    convenience: "الراحة",
    comfort: "الراحة",
    satisfaction: "الرضا",
    happiness: "السعادة",
    joy: "الفرح",
    pleasure: "المتعة",
    enjoyment: "الاستمتاع",
    fun: "المرح",
    entertainment: "الترفيه",
    amusement: "التسلية",
    recreation: "الترفيه",
    leisure: "وقت الفراغ",
    relaxation: "الاسترخاء",
    rest: "الراحة",
    break: "استراحة",
    pause: "توقف",
    stop: "توقف",
    end: "النهاية",
    finish: "الانتهاء",
    complete: "مكتمل",
    done: "تم",
    ready: "جاهز",
    available: "متاح",
    accessible: "قابل للوصول",
    reachable: "قابل للوصول",
    obtainable: "قابل للحصول عليه",
    achievable: "قابل للتحقيق",
    possible: "ممكن",
    feasible: "قابل للتنفيذ",
    viable: "قابل للحياة",
    practical: "عملي",
    realistic: "واقعي",
    reasonable: "معقول",
    logical: "منطقي",
    sensible: "منطقي",
    rational: "عقلاني",
    intelligent: "ذكي",
    smart: "ذكي",
    clever: "ذكي",
    wise: "حكيم",
    knowledgeable: "مطلع",
    informed: "مطلع",
    aware: "واعي",
    conscious: "واعي",
    alert: "متيقظ",
    attentive: "منتبه",
    focused: "مركز",
    concentrated: "مركز",
    dedicated: "مخصص",
    committed: "ملتزم",
    devoted: "مكرس",
    loyal: "مخلص",
    faithful: "مخلص",
    trustworthy: "جدير بالثقة",
    reliable: "موثوق",
    dependable: "يمكن الاعتماد عليه",
    consistent: "متسق",
    stable: "مستقر",
    steady: "ثابت",
    constant: "ثابت",
    continuous: "مستمر",
    ongoing: "مستمر",
    persistent: "مستمر",
    permanent: "دائم",
    lasting: "دائم",
    enduring: "دائم",
    eternal: "أبدي",
    infinite: "لا نهائي",
    unlimited: "غير محدود",
    boundless: "بلا حدود",
    endless: "لا نهاية له",
    countless: "لا يحصى",
    numerous: "عديد",
    multiple: "متعدد",
    various: "متنوع",
    different: "مختلف",
    diverse: "متنوع",
    varied: "متنوع",
    mixed: "مختلط",
    combined: "مدمج",
    integrated: "متكامل",
    unified: "موحد",
    connected: "متصل",
    linked: "مرتبط",
    related: "مرتبط",
    associated: "مرتبط",
    attached: "مرفق",
    joined: "منضم",
    merged: "مدمج",
    blended: "مخلوط",
    fused: "مدمج",
    synthesized: "مركب",
    composed: "مؤلف",
    constructed: "مبني",
    built: "مبني",
    created: "مُنشأ",
    made: "مصنوع",
    produced: "منتج",
    manufactured: "مصنع",
    generated: "مولد",
    developed: "مطور",
    designed: "مصمم",
    planned: "مخطط",
    organized: "منظم",
    arranged: "مرتب",
    structured: "منظم",
    formatted: "منسق",
    styled: "منسق",
    customized: "مخصص",
    personalized: "شخصي",
    individualized: "فردي",
    tailored: "مفصل",
    adapted: "مكيف",
    adjusted: "معدل",
    modified: "معدل",
    changed: "متغير",
    updated: "محدث",
    upgraded: "محدث",
    improved: "محسن",
    enhanced: "محسن",
    optimized: "محسن",
    refined: "مكرر",
    polished: "مصقول",
    perfected: "مكمل",
    finalized: "نهائي",
    completed: "مكتمل",
    finished: "منتهي",
    concluded: "مختتم",
    closed: "مغلق",
    sealed: "مختوم",
    locked: "مقفل",
    secured: "آمن",
    protected: "محمي",
    safe: "آمن",
    secure: "آمن",
    private: "خاص",
    confidential: "سري",
    classified: "مصنف",
    restricted: "مقيد",
    limited: "محدود",
    controlled: "مُتحكم فيه",
    managed: "مُدار",
    supervised: "مُشرف عليه",
    monitored: "مُراقب",
    tracked: "مُتتبع",
    measured: "مُقاس",
    evaluated: "مُقيم",
    assessed: "مُقدر",
    analyzed: "مُحلل",
    examined: "مُفحوص",
    inspected: "مُفتش",
    reviewed: "مُراجع",
    checked: "مُفحوص",
    verified: "مُتحقق منه",
    validated: "مُصدق",
    confirmed: "مُؤكد",
    approved: "مُوافق عليه",
    accepted: "مقبول",
    authorized: "مُخول",
    permitted: "مسموح",
    allowed: "مسموح",
    enabled: "مُمكن",
    activated: "مُفعل",
    turned_on: "مُشغل",
    started: "مُبدأ",
    launched: "مُطلق",
    initiated: "مُبدأ",
    begun: "مُبدأ",
    commenced: "مُبدأ",
    opened: "مفتوح",
    unlocked: "مفتوح",
    released: "مُحرر",
    published: "منشور",
    shared: "مُشارك",
    distributed: "موزع",
    delivered: "مُسلم",
    sent: "مُرسل",
    transmitted: "مُرسل",
    transferred: "منقول",
    moved: "منقول",
    relocated: "منقول",
    shifted: "منقول",
    transported: "منقول",
    carried: "محمول",
    brought: "مُحضر",
    taken: "مأخوذ",
    received: "مُستلم",
    obtained: "مُحصل عليه",
    acquired: "مُكتسب",
    gained: "مُكتسب",
    earned: "مُكتسب",
    achieved: "مُحقق",
    accomplished: "مُنجز",
    fulfilled: "مُحقق",
    realized: "مُحقق",
    attained: "مُحقق",
    reached: "وصل إليه",
    arrived: "وصل",
    came: "جاء",
    went: "ذهب",
    left: "غادر",
    departed: "غادر",
    exited: "خرج",
    entered: "دخل",
    joined: "انضم",
    participated: "شارك",
    contributed: "ساهم",
    helped: "ساعد",
    assisted: "ساعد",
    supported: "دعم",
    backed: "دعم",
    endorsed: "أيد",
    recommended: "أوصى",
    suggested: "اقترح",
    proposed: "اقترح",
    offered: "عرض",
    provided: "قدم",
    supplied: "زود",
    delivered: "سلم",
    gave: "أعطى",
    granted: "منح",
    awarded: "منح",
    presented: "قدم",
    showed: "أظهر",
    displayed: "عرض",
    exhibited: "عرض",
    demonstrated: "أظهر",
    illustrated: "وضح",
    explained: "شرح",
    described: "وصف",
    detailed: "فصل",
    specified: "حدد",
    defined: "عرف",
    identified: "حدد",
    recognized: "تعرف على",
    acknowledged: "اعترف",
    admitted: "اعترف",
    confessed: "اعترف",
    revealed: "كشف",
    disclosed: "كشف",
    exposed: "كشف",
    uncovered: "كشف",
    discovered: "اكتشف",
    found: "وجد",
    located: "حدد موقع",
    positioned: "وضع",
    placed: "وضع",
    put: "وضع",
    set: "وضع",
    installed: "ثبت",
    mounted: "ركب",
    attached: "ربط",
    connected: "وصل",
    linked: "ربط",
    joined: "ربط",
    combined: "دمج",
    merged: "دمج",
    integrated: "دمج",
    unified: "وحد",
    consolidated: "دمج",
    centralized: "مركز",
    organized: "نظم",
    arranged: "رتب",
    sorted: "رتب",
    ordered: "رتب",
    ranked: "رتب",
    classified: "صنف",
    categorized: "صنف",
    grouped: "جمع",
    collected: "جمع",
    gathered: "جمع",
    assembled: "جمع",
    compiled: "جمع",
    accumulated: "جمع",
    stored: "خزن",
    saved: "حفظ",
    preserved: "حفظ",
    maintained: "حافظ على",
    kept: "احتفظ",
    retained: "احتفظ",
    held: "احتفظ",
    owned: "امتلك",
    possessed: "امتلك",
    had: "كان لديه",
    contained: "احتوى",
    included: "تضمن",
    comprised: "تضمن",
    consisted: "تكون من",
    made_up: "تكون من",
    composed: "تكون من",
    formed: "شكل",
    created: "أنشأ",
    built: "بنى",
    constructed: "بنى",
    developed: "طور",
    produced: "أنتج",
    manufactured: "صنع",
    made: "صنع",
    generated: "ولد",
    caused: "سبب",
    resulted: "نتج",
    led: "أدى",
    brought: "جلب",
    induced: "حث",
    triggered: "أثار",
    activated: "فعل",
    initiated: "بدأ",
    started: "بدأ",
    began: "بدأ",
    commenced: "بدأ",
    launched: "أطلق",
    introduced: "قدم",
    presented: "قدم",
    announced: "أعلن",
    declared: "أعلن",
    stated: "صرح",
    said: "قال",
    told: "أخبر",
    informed: "أعلم",
    notified: "أخطر",
    alerted: "نبه",
    warned: "حذر",
    cautioned: "حذر",
    advised: "نصح",
    recommended: "أوصى",
    suggested: "اقترح",
    proposed: "اقترح",
    requested: "طلب",
    asked: "سأل",
    inquired: "استفسر",
    questioned: "سأل",
    wondered: "تساءل",
    doubted: "شك",
    suspected: "شك",
    believed: "اعتقد",
    thought: "اعتقد",
    considered: "اعتبر",
    regarded: "اعتبر",
    viewed: "نظر إلى",
    saw: "رأى",
    looked: "نظر",
    watched: "راقب",
    observed: "لاحظ",
    noticed: "لاحظ",
    detected: "اكتشف",
    spotted: "رصد",
    identified: "حدد",
    recognized: "تعرف على",
    distinguished: "ميز",
    differentiated: "ميز",
    separated: "فصل",
    divided: "قسم",
    split: "قسم",
    broke: "كسر",
    damaged: "أضر",
    harmed: "أضر",
    hurt: "آذى",
    injured: "جرح",
    wounded: "جرح",
    cut: "قطع",
    sliced: "قطع",
    chopped: "قطع",
    carved: "نحت",
    shaped: "شكل",
    molded: "شكل",
    formed: "شكل",
    designed: "صمم",
    planned: "خطط",
    prepared: "حضر",
    arranged: "رتب",
    organized: "نظم",
    managed: "أدار",
    controlled: "تحكم",
    operated: "شغل",
    ran: "شغل",
    worked: "عمل",
    functioned: "عمل",
    performed: "أدى",
    executed: "نفذ",
    carried_out: "نفذ",
    accomplished: "أنجز",
    achieved: "حقق",
    completed: "أكمل",
    finished: "انتهى",
    ended: "انتهى",
    concluded: "اختتم",
    closed: "أغلق",
    stopped: "توقف",
    ceased: "توقف",
    quit: "توقف",
    left: "ترك",
    abandoned: "هجر",
    gave_up: "استسلم",
    surrendered: "استسلم",
    yielded: "استسلم",
    submitted: "خضع",
    obeyed: "أطاع",
    followed: "تبع",
    pursued: "تابع",
    chased: "طارد",
    hunted: "طارد",
    searched: "بحث",
    looked_for: "بحث عن",
    sought: "سعى",
    tried: "حاول",
    attempted: "حاول",
    endeavored: "سعى",
    strived: "سعى",
    struggled: "كافح",
    fought: "قاتل",
    battled: "حارب",
    competed: "تنافس",
    contested: "تنافس",
    challenged: "تحدى",
    opposed: "عارض",
    resisted: "قاوم",
    defended: "دافع",
    protected: "حمى",
    guarded: "حرس",
    secured: "أمن",
    safeguarded: "حمى",
    preserved: "حافظ على",
    conserved: "حافظ على",
    maintained: "حافظ على",
    sustained: "حافظ على",
    supported: "دعم",
    backed: "دعم",
    endorsed: "أيد",
    approved: "وافق",
    accepted: "قبل",
    agreed: "وافق",
    consented: "وافق",
    permitted: "سمح",
    allowed: "سمح",
    authorized: "أذن",
    enabled: "مكن",
    empowered: "مكن",
    strengthened: "قوى",
    reinforced: "عزز",
    enhanced: "حسن",
    improved: "حسن",
    upgraded: "حسن",
    advanced: "تقدم",
    progressed: "تقدم",
    developed: "تطور",
    evolved: "تطور",
    grew: "نما",
    expanded: "توسع",
    extended: "مدد",
    stretched: "مدد",
    lengthened: "أطال",
    widened: "وسع",
    broadened: "وسع",
    enlarged: "كبر",
    increased: "زاد",
    raised: "رفع",
    lifted: "رفع",
    elevated: "رفع",
    boosted: "عزز",
    amplified: "ضخم",
    magnified: "كبر",
    multiplied: "ضاعف",
    doubled: "ضاعف",
    tripled: "ثلث",
    quadrupled: "ربع",
    maximized: "عظم",
    optimized: "حسن",
    minimized: "قلل",
    reduced: "قلل",
    decreased: "قلل",
    lowered: "خفض",
    dropped: "أسقط",
    fell: "سقط",
    declined: "انخفض",
    diminished: "تناقص",
    shrunk: "انكمش",
    contracted: "انقبض",
    compressed: "ضغط",
    squeezed: "عصر",
    pressed: "ضغط",
    pushed: "دفع",
    pulled: "سحب",
    dragged: "سحب",
    carried: "حمل",
    lifted: "رفع",
    moved: "حرك",
    shifted: "نقل",
    transferred: "نقل",
    transported: "نقل",
    delivered: "سلم",
    brought: "جلب",
    took: "أخذ",
    got: "حصل على",
    obtained: "حصل على",
    acquired: "اكتسب",
    gained: "كسب",
    earned: "كسب",
    won: "فاز",
    beat: "هزم",
    defeated: "هزم",
    conquered: "غزا",
    overcame: "تغلب على",
    succeeded: "نجح",
    accomplished: "أنجز",
    achieved: "حقق",
    attained: "بلغ",
    reached: "وصل",
    arrived: "وصل",
    came: "جاء",
    appeared: "ظهر",
    emerged: "ظهر",
    surfaced: "ظهر",
    arose: "نشأ",
    occurred: "حدث",
    happened: "حدث",
    took_place: "حدث",
    transpired: "حدث",
    unfolded: "تكشف",
    developed: "تطور",
    evolved: "تطور",
    changed: "تغير",
    transformed: "تحول",
    converted: "تحول",
    turned: "تحول",
    became: "أصبح",
    grew: "نما",
    matured: "نضج",
    aged: "شاخ",
    weathered: "تجوى",
    worn: "بلي",
    used: "استخدم",
    utilized: "استخدم",
    employed: "استخدم",
    applied: "طبق",
    implemented: "نفذ",
    executed: "نفذ",
    performed: "أدى",
    conducted: "أجرى",
    carried_out: "نفذ",
    accomplished: "أنجز",
    completed: "أكمل",
    finished: "انتهى",
    done: "انتهى",
    over: "انتهى",
    ended: "انتهى",
    concluded: "اختتم",
    closed: "أغلق",
    shut: "أغلق",
    sealed: "ختم",
    locked: "أقفل",
    secured: "أمن",
    fastened: "ربط",
    tied: "ربط",
    bound: "ربط",
    connected: "وصل",
    linked: "ربط",
    joined: "ربط",
    united: "وحد",
    combined: "دمج",
    merged: "دمج",
    blended: "خلط",
    mixed: "خلط",
    stirred: "حرك",
    shook: "هز",
    vibrated: "اهتز",
    trembled: "ارتعش",
    quivered: "ارتجف",
    shivered: "ارتعش",
    froze: "تجمد",
    chilled: "برد",
    cooled: "برد",
    heated: "سخن",
    warmed: "دفأ",
    burned: "احترق",
    ignited: "اشتعل",
    lit: "أضاء",
    illuminated: "أنار",
    brightened: "أضاء",
    darkened: "أظلم",
    dimmed: "خفت",
    faded: "بهت",
    disappeared: "اختفى",
    vanished: "اختفى",
    gone: "ذهب",
    left: "غادر",
    departed: "غادر",
    exited: "خرج",
    escaped: "هرب",
    fled: "فر",
    ran: "جرى",
    rushed: "أسرع",
    hurried: "أسرع",
    hastened: "أسرع",
    accelerated: "تسارع",
    sped: "أسرع",
    slowed: "أبطأ",
    decelerated: "تباطأ",
    stopped: "توقف",
    paused: "توقف مؤقتاً",
    waited: "انتظر",
    delayed: "أخر",
    postponed: "أجل",
    rescheduled: "أعاد جدولة",
    cancelled: "ألغى",
    terminated: "أنهى",
    discontinued: "توقف عن",
    suspended: "علق",
    interrupted: "قاطع",
    disturbed: "أزعج",
    bothered: "أزعج",
    annoyed: "أزعج",
    irritated: "أثار",
    frustrated: "أحبط",
    disappointed: "خيب",
    satisfied: "أرضى",
    pleased: "أسعد",
    delighted: "أسعد",
    thrilled: "أثار",
    excited: "أثار",
    enthusiastic: "متحمس",
    passionate: "شغوف",
    devoted: "مكرس",
    dedicated: "مخصص",
    committed: "ملتزم",
    loyal: "مخلص",
    faithful: "مخلص",
    honest: "صادق",
    truthful: "صادق",
    sincere: "صادق",
    genuine: "حقيقي",
    authentic: "أصيل",
    original: "أصلي",
    unique: "فريد",
    special: "خاص",
    exceptional: "استثنائي",
    extraordinary: "استثنائي",
    remarkable: "ملحوظ",
    outstanding: "متميز",
    excellent: "ممتاز",
    superb: "رائع",
    magnificent: "رائع",
    wonderful: "رائع",
    amazing: "مذهل",
    incredible: "لا يصدق",
    fantastic: "رائع",
    great: "عظيم",
    good: "جيد",
    fine: "جيد",
    okay: "حسناً",
    alright: "حسناً",
    bad: "سيء",
    poor: "ضعيف",
    terrible: "فظيع",
    awful: "فظيع",
    horrible: "مروع",
    dreadful: "مروع",
    frightening: "مخيف",
    scary: "مخيف",
    dangerous: "خطير",
    risky: "محفوف بالمخاطر",
    unsafe: "غير آمن",
    hazardous: "خطر",
    harmful: "ضار",
    damaging: "مضر",
    destructive: "مدمر",
    devastating: "مدمر",
    catastrophic: "كارثي",
    disastrous: "كارثي",
    tragic: "مأساوي",
    sad: "حزين",
    unhappy: "غير سعيد",
    miserable: "بائس",
    depressed: "مكتئب",
    gloomy: "كئيب",
    dark: "مظلم",
    bright: "مشرق",
    light: "فاتح",
    clear: "واضح",
    transparent: "شفاف",
    visible: "مرئي",
    obvious: "واضح",
    evident: "واضح",
    apparent: "ظاهر",
    manifest: "واضح",
    plain: "واضح",
    simple: "بسيط",
    easy: "سهل",
    difficult: "صعب",
    hard: "صعب",
    tough: "صعب",
    challenging: "تحدي",
    complex: "معقد",
    complicated: "معقد",
    intricate: "معقد",
    detailed: "مفصل",
    comprehensive: "شامل",
    complete: "كامل",
    full: "ممتلئ",
    empty: "فارغ",
    vacant: "شاغر",
    available: "متاح",
    free: "مجاني",
    open: "مفتوح",
    closed: "مغلق",
    locked: "مقفل",
    secured: "آمن",
    protected: "محمي",
    safe: "آمن",
    sound: "سليم",
    healthy: "صحي",
    fit: "لائق",
    strong: "قوي",
    powerful: "قوي",
    mighty: "قوي",
    weak: "ضعيف",
    fragile: "هش",
    delicate: "رقيق",
    gentle: "لطيف",
    soft: "ناعم",
    smooth: "أملس",
    rough: "خشن",
    coarse: "خشن",
    fine: "ناعم",
    thin: "رفيع",
    thick: "سميك",
    wide: "عريض",
    narrow: "ضيق",
    broad: "عريض",
    long: "طويل",
    short: "قصير",
    tall: "طويل",
    high: "عالي",
    low: "منخفض",
    deep: "عميق",
    shallow: "ضحل",
    big: "كبير",
    large: "كبير",
    huge: "ضخم",
    enormous: "هائل",
    gigantic: "عملاق",
    massive: "ضخم",
    tiny: "صغير جداً",
    small: "صغير",
    little: "صغير",
    mini: "صغير",
    micro: "مجهري",
    macro: "كبير",
    mega: "ضخم",
    super: "فائق",
    ultra: "فائق",
    extra: "إضافي",
    additional: "إضافي",
    more: "أكثر",
    less: "أقل",
    fewer: "أقل",
    many: "كثير",
    much: "كثير",
    lot: "كثير",
    plenty: "كثير",
    enough: "كافي",
    sufficient: "كافي",
    adequate: "كافي",
    insufficient: "غير كافي",
    lacking: "ناقص",
    missing: "مفقود",
    absent: "غائب",
    present: "حاضر",
    here: "هنا",
    there: "هناك",
    everywhere: "في كل مكان",
    nowhere: "لا مكان",
    somewhere: "في مكان ما",
    anywhere: "في أي مكان",
    always: "دائماً",
    never: "أبداً",
    sometimes: "أحياناً",
    often: "غالباً",
    rarely: "نادراً",
    seldom: "نادراً",
    frequently: "بكثرة",
    occasionally: "أحياناً",
    regularly: "بانتظام",
    constantly: "باستمرار",
    continuously: "باستمرار",
    permanently: "بشكل دائم",
    temporarily: "مؤقتاً",
    briefly: "لفترة وجيزة",
    quickly: "بسرعة",
    slowly: "ببطء",
    fast: "سريع",
    rapid: "سريع",
    swift: "سريع",
    speedy: "سريع",
    slow: "بطيء",
    gradual: "تدريجي",
    sudden: "مفاجئ",
    immediate: "فوري",
    instant: "فوري",
    direct: "مباشر",
    indirect: "غير مباشر",
    straight: "مستقيم",
    curved: "منحني",
    bent: "منحني",
    twisted: "ملتوي",
    crooked: "معوج",
    round: "دائري",
    circular: "دائري",
    square: "مربع",
    rectangular: "مستطيل",
    triangular: "مثلث",
    oval: "بيضاوي",
    flat: "مسطح",
    level: "مستوي",
    even: "متساوي",
    uneven: "غير متساوي",
    balanced: "متوازن",
    unbalanced: "غير متوازن",
    stable: "مستقر",
    unstable: "غير مستقر",
    steady: "ثابت",
    unsteady: "غير ثابت",
    firm: "ثابت",
    solid: "صلب",
    liquid: "سائل",
    gas: "غاز",
    hot: "ساخن",
    warm: "دافئ",
    cool: "بارد",
    cold: "بارد",
    freezing: "متجمد",
    boiling: "يغلي",
    wet: "مبلل",
    dry: "جاف",
    moist: "رطب",
    damp: "رطب",
    humid: "رطب",
    fresh: "طازج",
    stale: "قديم",
    new: "جديد",
    old: "قديم",
    ancient: "قديم جداً",
    modern: "حديث",
    contemporary: "معاصر",
    current: "حالي",
    recent: "حديث",
    past: "ماضي",
    future: "مستقبل",
    today: "اليوم",
    yesterday: "أمس",
    tomorrow: "غداً",
    now: "الآن",
    then: "ثم",
    later: "لاحقاً",
    earlier: "في وقت سابق",
    before: "قبل",
    after: "بعد",
    during: "أثناء",
    while: "بينما",
    when: "عندما",
    where: "أين",
    why: "لماذا",
    how: "كيف",
    what: "ماذا",
    which: "أي",
    who: "من",
    whose: "لمن",
    whom: "لمن",
  },
  en: {
    home: "Home",
    products: "Products",
    categories: "Categories",
    cart: "Cart",
    search: "Search",
    login: "Login",
    register: "Register",
    profile: "Profile",
    orders: "Orders",
    settings: "Settings",
    logout: "Logout",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    price: "Price",
    description: "Description",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    trackOrder: "Track Order",
    orderCode: "Order Code",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    customerPhone: "Customer Phone",
    customerAddress: "Customer Address",
    orderStatus: "Order Status",
    paymentStatus: "Payment Status",
    pending: "Pending",
    processing: "Processing",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    paid: "Paid",
    failed: "Failed",
    cash: "Cash",
    card: "Card",
    admin: "Admin",
    dashboard: "Dashboard",
    manageProducts: "Manage Products",
    manageCategories: "Manage Categories",
    manageOrders: "Manage Orders",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    deleteProduct: "Delete Product",
    addCategory: "Add Category",
    editCategory: "Edit Category",
    deleteCategory: "Delete Category",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    name: "Name",
    image: "Image",
    category: "Category",
    createdAt: "Created At",
    updatedAt: "Updated At",
    actions: "Actions",
    noData: "No Data",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    close: "Close",
    next: "Next",
    previous: "Previous",
    first: "First",
    last: "Last",
    page: "Page",
    of: "of",
    total: "Total",
    items: "Items",
    showing: "Showing",
    to: "to",
    results: "Results",
    noResults: "No Results",
    searchPlaceholder: "Search products...",
    filterBy: "Filter By",
    sortBy: "Sort By",
    newest: "Newest",
    oldest: "Oldest",
    priceHighToLow: "Price High to Low",
    priceLowToHigh: "Price Low to High",
    nameAZ: "Name A-Z",
    nameZA: "Name Z-A",
    all: "All",
    featured: "Featured",
    newArrivals: "New Arrivals",
    bestSellers: "Best Sellers",
    onSale: "On Sale",
    clearFilters: "Clear Filters",
    applyFilters: "Apply Filters",
    showMore: "Show More",
    showLess: "Show Less",
    readMore: "Read More",
    readLess: "Read Less",
    share: "Share",
    wishlist: "Wishlist",
    compare: "Compare",
    quickView: "Quick View",
    addToWishlist: "Add to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    addToCompare: "Add to Compare",
    removeFromCompare: "Remove from Compare",
    checkout: "Checkout",
    continueShopping: "Continue Shopping",
    emptyCart: "Empty Cart",
    cartTotal: "Cart Total",
    subtotal: "Subtotal",
    tax: "Tax",
    shipping: "Shipping",
    discount: "Discount",
    coupon: "Coupon",
    applyCoupon: "Apply Coupon",
    removeCoupon: "Remove Coupon",
    quantity: "Quantity",
    remove: "Remove",
    update: "Update",
    updateCart: "Update Cart",
    proceedToCheckout: "Proceed to Checkout",
    backToCart: "Back to Cart",
    orderSummary: "Order Summary",
    billingAddress: "Billing Address",
    shippingAddress: "Shipping Address",
    paymentMethod: "Payment Method",
    placeOrder: "Place Order",
    orderPlaced: "Order Placed",
    orderNumber: "Order Number",
    orderDate: "Order Date",
    estimatedDelivery: "Estimated Delivery",
    trackYourOrder: "Track Your Order",
    orderDetails: "Order Details",
    shippingDetails: "Shipping Details",
    paymentDetails: "Payment Details",
    contactUs: "Contact Us",
    aboutUs: "About Us",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    faq: "FAQ",
    support: "Support",
    newsletter: "Newsletter",
    subscribe: "Subscribe",
    unsubscribe: "Unsubscribe",
    followUs: "Follow Us",
    socialMedia: "Social Media",
    facebook: "Facebook",
    twitter: "Twitter",
    instagram: "Instagram",
    youtube: "YouTube",
    linkedin: "LinkedIn",
    copyright: "All Rights Reserved",
    poweredBy: "Powered By",
    version: "Version",
    language: "Language",
    currency: "Currency",
    country: "Country",
    region: "Region",
    timezone: "Timezone",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemMode: "System Mode",
    notifications: "Notifications",
    emailNotifications: "Email Notifications",
    smsNotifications: "SMS Notifications",
    pushNotifications: "Push Notifications",
    account: "Account",
    personalInfo: "Personal Info",
    changePassword: "Change Password",
    deleteAccount: "Delete Account",
    twoFactorAuth: "Two Factor Auth",
    loginHistory: "Login History",
    connectedAccounts: "Connected Accounts",
    dataExport: "Data Export",
    dataImport: "Data Import",
    backup: "Backup",
    restore: "Restore",
    maintenance: "Maintenance",
    systemStatus: "System Status",
    uptime: "Uptime",
    performance: "Performance",
    analytics: "Analytics",
    reports: "Reports",
    statistics: "Statistics",
    metrics: "Metrics",
    logs: "Logs",
    audit: "Audit",
    security: "Security",
    permissions: "Permissions",
    roles: "Roles",
    users: "Users",
    groups: "Groups",
    teams: "Teams",
    organizations: "Organizations",
    departments: "Departments",
    branches: "Branches",
    locations: "Locations",
    warehouses: "Warehouses",
    inventory: "Inventory",
    stock: "Stock",
    suppliers: "Suppliers",
    vendors: "Vendors",
    customers: "Customers",
    clients: "Clients",
    partners: "Partners",
    affiliates: "Affiliates",
    resellers: "Resellers",
    distributors: "Distributors",
    retailers: "Retailers",
    wholesalers: "Wholesalers",
    manufacturers: "Manufacturers",
    brands: "Brands",
    models: "Models",
    variants: "Variants",
    options: "Options",
    attributes: "Attributes",
    specifications: "Specifications",
    features: "Features",
    benefits: "Benefits",
    advantages: "Advantages",
    disadvantages: "Disadvantages",
    pros: "Pros",
    cons: "Cons",
    reviews: "Reviews",
    ratings: "Ratings",
    comments: "Comments",
    feedback: "Feedback",
    testimonials: "Testimonials",
    recommendations: "Recommendations",
    suggestions: "Suggestions",
    complaints: "Complaints",
    issues: "Issues",
    bugs: "Bugs",
    fixes: "Fixes",
    updates: "Updates",
    upgrades: "Upgrades",
    patches: "Patches",
    releases: "Releases",
    versions: "Versions",
    changelog: "Changelog",
    roadmap: "Roadmap",
    milestones: "Milestones",
    goals: "Goals",
    objectives: "Objectives",
    targets: "Targets",
    kpis: "KPIs",
    metrics: "Metrics",
    benchmarks: "Benchmarks",
    standards: "Standards",
    guidelines: "Guidelines",
    policies: "Policies",
    procedures: "Procedures",
    processes: "Processes",
    workflows: "Workflows",
    automation: "Automation",
    integration: "Integration",
    synchronization: "Synchronization",
    migration: "Migration",
    transformation: "Transformation",
    optimization: "Optimization",
    enhancement: "Enhancement",
    improvement: "Improvement",
    innovation: "Innovation",
    development: "Development",
    research: "Research",
    testing: "Testing",
    validation: "Validation",
    verification: "Verification",
    certification: "Certification",
    compliance: "Compliance",
    governance: "Governance",
    risk: "Risk",
    mitigation: "Mitigation",
    prevention: "Prevention",
    protection: "Protection",
    safety: "Safety",
    health: "Health",
    environment: "Environment",
    sustainability: "Sustainability",
    responsibility: "Responsibility",
    ethics: "Ethics",
    values: "Values",
    principles: "Principles",
    culture: "Culture",
    mission: "Mission",
    vision: "Vision",
    strategy: "Strategy",
    planning: "Planning",
    execution: "Execution",
    monitoring: "Monitoring",
    evaluation: "Evaluation",
    assessment: "Assessment",
    measurement: "Measurement",
    tracking: "Tracking",
    progress: "Progress",
    status: "Status",
    condition: "Condition",
    state: "State",
    phase: "Phase",
    stage: "Stage",
    step: "Step",
    level: "Level",
    grade: "Grade",
    rank: "Rank",
    position: "Position",
    location: "Location",
    address: "Address",
    coordinates: "Coordinates",
    map: "Map",
    directions: "Directions",
    navigation: "Navigation",
    route: "Route",
    path: "Path",
    journey: "Journey",
    trip: "Trip",
    travel: "Travel",
    transport: "Transport",
    delivery: "Delivery",
    shipping: "Shipping",
    logistics: "Logistics",
    fulfillment: "Fulfillment",
    processing: "Processing",
    handling: "Handling",
    management: "Management",
    administration: "Administration",
    operation: "Operation",
    maintenance: "Maintenance",
    service: "Service",
    support: "Support",
    assistance: "Assistance",
    help: "Help",
    guidance: "Guidance",
    instruction: "Instruction",
    tutorial: "Tutorial",
    guide: "Guide",
    manual: "Manual",
    documentation: "Documentation",
    reference: "Reference",
    resource: "Resource",
    tool: "Tool",
    utility: "Utility",
    application: "Application",
    software: "Software",
    program: "Program",
    system: "System",
    platform: "Platform",
    framework: "Framework",
    library: "Library",
    module: "Module",
    component: "Component",
    element: "Element",
    item: "Item",
    object: "Object",
    entity: "Entity",
    record: "Record",
    entry: "Entry",
    data: "Data",
    information: "Information",
    content: "Content",
    material: "Material",
    resource: "Resource",
    asset: "Asset",
    property: "Property",
    attribute: "Attribute",
    field: "Field",
    column: "Column",
    row: "Row",
    table: "Table",
    list: "List",
    array: "Array",
    collection: "Collection",
    set: "Set",
    group: "Group",
    cluster: "Cluster",
    bundle: "Bundle",
    package: "Package",
    container: "Container",
    wrapper: "Wrapper",
    envelope: "Envelope",
    box: "Box",
    folder: "Folder",
    directory: "Directory",
    file: "File",
    document: "Document",
    report: "Report",
    summary: "Summary",
    overview: "Overview",
    preview: "Preview",
    sample: "Sample",
    example: "Example",
    demo: "Demo",
    prototype: "Prototype",
    template: "Template",
    pattern: "Pattern",
    format: "Format",
    structure: "Structure",
    layout: "Layout",
    design: "Design",
    style: "Style",
    appearance: "Appearance",
    look: "Look",
    feel: "Feel",
    experience: "Experience",
    interface: "Interface",
    interaction: "Interaction",
    behavior: "Behavior",
    functionality: "Functionality",
    capability: "Capability",
    capacity: "Capacity",
    performance: "Performance",
    efficiency: "Efficiency",
    effectiveness: "Effectiveness",
    productivity: "Productivity",
    quality: "Quality",
    reliability: "Reliability",
    stability: "Stability",
    consistency: "Consistency",
    accuracy: "Accuracy",
    precision: "Precision",
    correctness: "Correctness",
    validity: "Validity",
    integrity: "Integrity",
    completeness: "Completeness",
    availability: "Availability",
    accessibility: "Accessibility",
    usability: "Usability",
    convenience: "Convenience",
    comfort: "Comfort",
    satisfaction: "Satisfaction",
    happiness: "Happiness",
    joy: "Joy",
    pleasure: "Pleasure",
    enjoyment: "Enjoyment",
    fun: "Fun",
    entertainment: "Entertainment",
    amusement: "Amusement",
    recreation: "Recreation",
    leisure: "Leisure",
    relaxation: "Relaxation",
    rest: "Rest",
    break: "Break",
    pause: "Pause",
    stop: "Stop",
    end: "End",
    finish: "Finish",
    complete: "Complete",
    done: "Done",
    ready: "Ready",
    available: "Available",
    accessible: "Accessible",
    reachable: "Reachable",
    obtainable: "Obtainable",
    achievable: "Achievable",
    possible: "Possible",
    feasible: "Feasible",
    viable: "Viable",
    practical: "Practical",
    realistic: "Realistic",
    reasonable: "Reasonable",
    logical: "Logical",
    sensible: "Sensible",
    rational: "Rational",
    intelligent: "Intelligent",
    smart: "Smart",
    clever: "Clever",
    wise: "Wise",
    knowledgeable: "Knowledgeable",
    informed: "Informed",
    aware: "Aware",
    conscious: "Conscious",
    alert: "Alert",
    attentive: "Attentive",
    focused: "Focused",
    concentrated: "Concentrated",
    dedicated: "Dedicated",
    committed: "Committed",
    devoted: "Devoted",
    loyal: "Loyal",
    faithful: "Faithful",
    trustworthy: "Trustworthy",
    reliable: "Reliable",
    dependable: "Dependable",
    consistent: "Consistent",
    stable: "Stable",
    steady: "Steady",
    constant: "Constant",
    continuous: "Continuous",
    ongoing: "Ongoing",
    persistent: "Persistent",
    permanent: "Permanent",
    lasting: "Lasting",
    enduring: "Enduring",
    eternal: "Eternal",
    infinite: "Infinite",
    unlimited: "Unlimited",
    boundless: "Boundless",
    endless: "Endless",
    countless: "Countless",
    numerous: "Numerous",
    multiple: "Multiple",
    various: "Various",
    different: "Different",
    diverse: "Diverse",
    varied: "Varied",
    mixed: "Mixed",
    combined: "Combined",
    integrated: "Integrated",
    unified: "Unified",
    connected: "Connected",
    linked: "Linked",
    related: "Related",
    associated: "Associated",
    attached: "Attached",
    joined: "Joined",
    merged: "Merged",
    blended: "Blended",
    fused: "Fused",
    synthesized: "Synthesized",
    composed: "Composed",
    constructed: "Constructed",
    built: "Built",
    created: "Created",
    made: "Made",
    produced: "Produced",
    manufactured: "Manufactured",
    generated: "Generated",
    developed: "Developed",
    designed: "Designed",
    planned: "Planned",
    organized: "Organized",
    arranged: "Arranged",
    structured: "Structured",
    formatted: "Formatted",
    styled: "Styled",
    customized: "Customized",
    personalized: "Personalized",
    individualized: "Individualized",
    tailored: "Tailored",
    adapted: "Adapted",
    adjusted: "Adjusted",
    modified: "Modified",
    changed: "Changed",
    updated: "Updated",
    upgraded: "Upgraded",
    improved: "Improved",
    enhanced: "Enhanced",
    optimized: "Optimized",
    refined: "Refined",
    polished: "Polished",
    perfected: "Perfected",
    finalized: "Finalized",
    completed: "Completed",
    finished: "Finished",
    concluded: "Concluded",
    closed: "Closed",
    sealed: "Sealed",
    locked: "Locked",
    secured: "Secured",
    protected: "Protected",
    safe: "Safe",
    secure: "Secure",
    private: "Private",
    confidential: "Confidential",
    classified: "Classified",
    restricted: "Restricted",
    limited: "Limited",
    controlled: "Controlled",
    managed: "Managed",
    supervised: "Supervised",
    monitored: "Monitored",
    tracked: "Tracked",
    measured: "Measured",
    evaluated: "Evaluated",
    assessed: "Assessed",
    analyzed: "Analyzed",
    examined: "Examined",
    inspected: "Inspected",
    reviewed: "Reviewed",
    checked: "Checked",
    verified: "Verified",
    validated: "Validated",
    confirmed: "Confirmed",
    approved: "Approved",
    accepted: "Accepted",
    authorized: "Authorized",
    permitted: "Permitted",
    allowed: "Allowed",
    enabled: "Enabled",
    activated: "Activated",
    turned_on: "Turned On",
    started: "Started",
    launched: "Launched",
    initiated: "Initiated",
    begun: "Begun",
    commenced: "Commenced",
    opened: "Opened",
    unlocked: "Unlocked",
    released: "Released",
    published: "Published",
    shared: "Shared",
    distributed: "Distributed",
    delivered: "Delivered",
    sent: "Sent",
    transmitted: "Transmitted",
    transferred: "Transferred",
    moved: "Moved",
    relocated: "Relocated",
    shifted: "Shifted",
    transported: "Transported",
    carried: "Carried",
    brought: "Brought",
    taken: "Taken",
    received: "Received",
    obtained: "Obtained",
    acquired: "Acquired",
    gained: "Gained",
    earned: "Earned",
    achieved: "Achieved",
    accomplished: "Accomplished",
    fulfilled: "Fulfilled",
    realized: "Realized",
    attained: "Attained",
    reached: "Reached",
    arrived: "Arrived",
    came: "Came",
    went: "Went",
    left: "Left",
    departed: "Departed",
    exited: "Exited",
    entered: "Entered",
    joined: "Joined",
    participated: "Participated",
    contributed: "Contributed",
    helped: "Helped",
    assisted: "Assisted",
    supported: "Supported",
    backed: "Backed",
    endorsed: "Endorsed",
    recommended: "Recommended",
    suggested: "Suggested",
    proposed: "Proposed",
    offered: "Offered",
    provided: "Provided",
    supplied: "Supplied",
    delivered: "Delivered",
    gave: "Gave",
    granted: "Granted",
    awarded: "Awarded",
    presented: "Presented",
    showed: "Showed",
    displayed: "Displayed",
    exhibited: "Exhibited",
    demonstrated: "Demonstrated",
    illustrated: "Illustrated",
    explained: "Explained",
    described: "Described",
    detailed: "Detailed",
    specified: "Specified",
    defined: "Defined",
    identified: "Identified",
    recognized: "Recognized",
    acknowledged: "Acknowledged",
    admitted: "Admitted",
    confessed: "Confessed",
    revealed: "Revealed",
    disclosed: "Disclosed",
    exposed: "Exposed",
    uncovered: "Uncovered",
    discovered: "Discovered",
    found: "Found",
    located: "Located",
    positioned: "Positioned",
    placed: "Placed",
    put: "Put",
    set: "Set",
    installed: "Installed",
    mounted: "Mounted",
    attached: "Attached",
    connected: "Connected",
    linked: "Linked",
    joined: "Joined",
    combined: "Combined",
    merged: "Merged",
    integrated: "Integrated",
    unified: "Unified",
    consolidated: "Consolidated",
    centralized: "Centralized",
    organized: "Organized",
    arranged: "Arranged",
    sorted: "Sorted",
    ordered: "Ordered",
    ranked: "Ranked",
    classified: "Classified",
    categorized: "Categorized",
    grouped: "Grouped",
    collected: "Collected",
    gathered: "Gathered",
    assembled: "Assembled",
    compiled: "Compiled",
    accumulated: "Accumulated",
    stored: "Stored",
    saved: "Saved",
    preserved: "Preserved",
    maintained: "Maintained",
    kept: "Kept",
    retained: "Retained",
    held: "Held",
    owned: "Owned",
    possessed: "Possessed",
    had: "Had",
    contained: "Contained",
    included: "Included",
    comprised: "Comprised",
    consisted: "Consisted",
    made_up: "Made Up",
    composed: "Composed",
    formed: "Formed",
    created: "Created",
    built: "Built",
    constructed: "Constructed",
    developed: "Developed",
    produced: "Produced",
    manufactured: "Manufactured",
    made: "Made",
    generated: "Generated",
    caused: "Caused",
    resulted: "Resulted",
    led: "Led",
    brought: "Brought",
    induced: "Induced",
    triggered: "Triggered",
    activated: "Activated",
    initiated: "Initiated",
    started: "Started",
    began: "Began",
    commenced: "Commenced",
    launched: "Launched",
    introduced: "Introduced",
    presented: "Presented",
    announced: "Announced",
    declared: "Declared",
    stated: "Stated",
    said: "Said",
    told: "Told",
    informed: "Informed",
    notified: "Notified",
    alerted: "Alerted",
    warned: "Warned",
    cautioned: "Cautioned",
    advised: "Advised",
    recommended: "Recommended",
    suggested: "Suggested",
    proposed: "Proposed",
    requested: "Requested",
    asked: "Asked",
    inquired: "Inquired",
    questioned: "Questioned",
    wondered: "Wondered",
    doubted: "Doubted",
    suspected: "Suspected",
    believed: "Believed",
    thought: "Thought",
    considered: "Considered",
    regarded: "Regarded",
    viewed: "Viewed",
    saw: "Saw",
    looked: "Looked",
    watched: "Watched",
    observed: "Observed",
    noticed: "Noticed",
    detected: "Detected",
    spotted: "Spotted",
    identified: "Identified",
    recognized: "Recognized",
    distinguished: "Distinguished",
    differentiated: "Differentiated",
    separated: "Separated",
    divided: "Divided",
    split: "Split",
    broke: "Broke",
    damaged: "Damaged",
    harmed: "Harmed",
    hurt: "Hurt",
    injured: "Injured",
    wounded: "Wounded",
    cut: "Cut",
    sliced: "Sliced",
    chopped: "Chopped",
    carved: "Carved",
    shaped: "Shaped",
    molded: "Molded",
    formed: "Formed",
    designed: "Designed",
    planned: "Planned",
    prepared: "Prepared",
    arranged: "Arranged",
    organized: "Organized",
    managed: "Managed",
    controlled: "Controlled",
    operated: "Operated",
    ran: "Ran",
    worked: "Worked",
    functioned: "Functioned",
    performed: "Performed",
    executed: "Executed",
    carried_out: "Carried Out",
    accomplished: "Accomplished",
    achieved: "Achieved",
    completed: "Completed",
    finished: "Finished",
    ended: "Ended",
    concluded: "Concluded",
    closed: "Closed",
    stopped: "Stopped",
    ceased: "Ceased",
    quit: "Quit",
    left: "Left",
    abandoned: "Abandoned",
    gave_up: "Gave Up",
    surrendered: "Surrendered",
    yielded: "Yielded",
    submitted: "Submitted",
    obeyed: "Obeyed",
    followed: "Followed",
    pursued: "Pursued",
    chased: "Chased",
    hunted: "Hunted",
    searched: "Searched",
    looked_for: "Looked For",
    sought: "Sought",
    tried: "Tried",
    attempted: "Attempted",
    endeavored: "Endeavored",
    strived: "Strived",
    struggled: "Struggled",
    fought: "Fought",
    battled: "Battled",
    competed: "Competed",
    contested: "Contested",
    challenged: "Challenged",
    opposed: "Opposed",
    resisted: "Resisted",
    defended: "Defended",
    protected: "Protected",
    guarded: "Guarded",
    secured: "Secured",
    safeguarded: "Safeguarded",
    preserved: "Preserved",
    conserved: "Conserved",
    maintained: "Maintained",
    sustained: "Sustained",
    supported: "Supported",
    backed: "Backed",
    endorsed: "Endorsed",
    approved: "Approved",
    accepted: "Accepted",
    agreed: "Agreed",
    consented: "Consented",
    permitted: "Permitted",
    allowed: "Allowed",
    authorized: "Authorized",
    enabled: "Enabled",
    empowered: "Empowered",
    strengthened: "Strengthened",
    reinforced: "Reinforced",
    enhanced: "Enhanced",
    improved: "Improved",
    upgraded: "Upgraded",
    advanced: "Advanced",
    progressed: "Progressed",
    developed: "Developed",
    evolved: "Evolved",
    grew: "Grew",
    expanded: "Expanded",
    extended: "Extended",
    stretched: "Stretched",
    lengthened: "Lengthened",
    widened: "Widened",
    broadened: "Broadened",
    enlarged: "Enlarged",
    increased: "Increased",
    raised: "Raised",
    lifted: "Lifted",
    elevated: "Elevated",
    boosted: "Boosted",
    amplified: "Amplified",
    magnified: "Magnified",
    multiplied: "Multiplied",
    doubled: "Doubled",
    tripled: "Tripled",
    quadrupled: "Quadrupled",
    maximized: "Maximized",
    optimized: "Optimized",
    minimized: "Minimized",
    reduced: "Reduced",
    decreased: "Decreased",
    lowered: "Lowered",
    dropped: "Dropped",
    fell: "Fell",
    declined: "Declined",
    diminished: "Diminished",
    shrunk: "Shrunk",
    contracted: "Contracted",
    compressed: "Compressed",
    squeezed: "Squeezed",
    pressed: "Pressed",
    pushed: "Pushed",
    pulled: "Pulled",
    dragged: "Dragged",
    carried: "Carried",
    lifted: "Lifted",
    moved: "Moved",
    shifted: "Shifted",
    transferred: "Transferred",
    transported: "Transported",
    delivered: "Delivered",
    brought: "Brought",
    took: "Took",
    got: "Got",
    obtained: "Obtained",
    acquired: "Acquired",
    gained: "Gained",
    earned: "Earned",
    won: "Won",
    beat: "Beat",
    defeated: "Defeated",
    conquered: "Conquered",
    overcame: "Overcame",
    succeeded: "Succeeded",
    accomplished: "Accomplished",
    achieved: "Achieved",
    attained: "Attained",
    reached: "Reached",
    arrived: "Arrived",
    came: "Came",
    appeared: "Appeared",
    emerged: "Emerged",
    surfaced: "Surfaced",
    arose: "Arose",
    occurred: "Occurred",
    happened: "Happened",
    took_place: "Took Place",
    transpired: "Transpired",
    unfolded: "Unfolded",
    developed: "Developed",
    evolved: "Evolved",
    changed: "Changed",
    transformed: "Transformed",
    converted: "Converted",
    turned: "Turned",
    became: "Became",
    grew: "Grew",
    matured: "Matured",
    aged: "Aged",
    weathered: "Weathered",
    worn: "Worn",
    used: "Used",
    utilized: "Utilized",
    employed: "Employed",
    applied: "Applied",
    implemented: "Implemented",
    executed: "Executed",
    performed: "Performed",
    conducted: "Conducted",
    carried_out: "Carried Out",
    accomplished: "Accomplished",
    completed: "Completed",
    finished: "Finished",
    done: "Done",
    over: "Over",
    ended: "Ended",
    concluded: "Concluded",
    closed: "Closed",
    shut: "Shut",
    sealed: "Sealed",
    locked: "Locked",
    secured: "Secured",
    fastened: "Fastened",
    tied: "Tied",
    bound: "Bound",
    connected: "Connected",
    linked: "Linked",
    joined: "Joined",
    united: "United",
    combined: "Combined",
    merged: "Merged",
    blended: "Blended",
    mixed: "Mixed",
    stirred: "Stirred",
    shook: "Shook",
    vibrated: "Vibrated",
    trembled: "Trembled",
    quivered: "Quivered",
    shivered: "Shivered",
    froze: "Froze",
    chilled: "Chilled",
    cooled: "Cooled",
    heated: "Heated",
    warmed: "Warmed",
    burned: "Burned",
    ignited: "Ignited",
    lit: "Lit",
    illuminated: "Illuminated",
    brightened: "Brightened",
    darkened: "Darkened",
    dimmed: "Dimmed",
    faded: "Faded",
    disappeared: "Disappeared",
    vanished: "Vanished",
    gone: "Gone",
    left: "Left",
    departed: "Departed",
    exited: "Exited",
    escaped: "Escaped",
    fled: "Fled",
    ran: "Ran",
    rushed: "Rushed",
    hurried: "Hurried",
    hastened: "Hastened",
    accelerated: "Accelerated",
    sped: "Sped",
    slowed: "Slowed",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(languages[0])

  const t = (key: string): string => {
    return translations[language.code]?.[key] || key
  }

  useEffect(() => {
    document.documentElement.lang = language.code
    document.documentElement.dir = language.direction
  }, [language])

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
      <LanguageProvider>
        {children}
        <Toaster />
      </LanguageProvider>
    </ThemeProvider>
  )
}
