
// constants/lang.ts
export const LANGUAGES = ["EN", "FR", "AR"] as const;
export type Language = (typeof LANGUAGES)[number];

// constant/lang.ts
export const translations = {
  en: {
    // contact
    contactUs: "Contact Us",
    back: "Back",
    whatsapp: "WhatsApp",
    email: "Email",
    // dashbord 
    dashboardTitle: "Admin Dashboard",
    welcomeMessage: "Welcome back! Here’s what’s happening with your store today.",
    totalOrders: "Total Orders",
    allOrders: "All orders to date",
    totalProducts: "Total Products",
    availableProducts: "Products currently available",
    categories: "Categories",
    activeCategories: "Active product categories",
    totalRevenue: "Total Revenue",
    completedOrders: "Revenue from completed orders",
    orderStatusDistribution: "Order Status Distribution",
    ordersByStatus: "Here's a breakdown of orders by status.",
    recentOrders: "Recent Orders",
    last5Orders: "The latest 5 orders placed in your store.",
    noOrders: "No recent orders available.",
    quickActions: "Quick Actions",
    quickAccess: "Access key sections of your store quickly.",
    manageOrders: "Manage Orders",
    manageProducts: "Manage Products",
    manageCategories: "Manage Categories",
    accountSettings: "Account Settings",
    statsFetchError: "Failed to fetch dashboard statistics.",
    processing: "Processing",
    paymentPending: "Payment Pending",
    paid: "Paid",
    confirmed: "Confirmed",
    rejected: "Rejected",
    delivered: "Delivered",

},
  fr: {
    // contact
    contactUs: "Contactez-nous",
    back: "Retour",
    whatsapp: "WhatsApp",
    email: "E-mail",
    // dashboard
     dashboardTitle: "Tableau de bord Admin",
    welcomeMessage: "Bon retour ! Voici ce qui se passe dans votre boutique aujourd'hui.",
    totalOrders: "Commandes totales",
    allOrders: "Toutes les commandes à ce jour",
    totalProducts: "Produits totaux",
    availableProducts: "Produits actuellement disponibles",
    categories: "Catégories",
    activeCategories: "Catégories de produits actives",
    totalRevenue: "Revenu total",
    completedOrders: "Revenu des commandes terminées",
    orderStatusDistribution: "Répartition des statuts des commandes",
    ordersByStatus: "Voici une répartition des commandes par statut.",
    recentOrders: "Commandes récentes",
    last5Orders: "Les 5 dernières commandes passées dans votre boutique.",
    noOrders: "Aucune commande récente disponible.",
    quickActions: "Actions rapides",
    quickAccess: "Accédez rapidement aux sections clés de votre boutique.",
    manageOrders: "Gérer les commandes",
    manageProducts: "Gérer les produits",
    manageCategories: "Gérer les catégories",
    accountSettings: "Paramètres du compte",
    statsFetchError: "Échec de la récupération des statistiques du tableau de bord.",
    processing: "En traitement",
    paymentPending: "Paiement en attente",
    paid: "Payé",
    confirmed: "Confirmé",
    rejected: "Rejeté",
    delivered: "Livré",
  },
  ar: {
    // contact
    contactUs: "اتصل بنا",
    back: "العودة",
    whatsapp: "واتساب",
    email: "البريد الإلكتروني",
    // dashboard
    dashboardTitle: "لوحة تحكم المدير",
    welcomeMessage: "مرحباً بعودتك! إليك ما يحدث في متجرك اليوم.",
    totalOrders: "إجمالي الطلبات",
    allOrders: "جميع الطلبات حتى الآن",
    totalProducts: "إجمالي المنتجات",
    availableProducts: "المنتجات المتوفرة حالياً",
    categories: "الفئات",
    activeCategories: "الفئات النشطة",
    totalRevenue: "إجمالي الإيرادات",
    completedOrders: "الإيرادات من الطلبات المكتملة",
    orderStatusDistribution: "توزيع حالة الطلبات",
    ordersByStatus: "إليك توزيع الطلبات حسب الحالة.",
    recentOrders: "أحدث الطلبات",
    last5Orders: "آخر 5 طلبات تم تقديمها في متجرك.",
    noOrders: "لا توجد طلبات حديثة.",
    quickActions: "إجراءات سريعة",
    quickAccess: "الوصول السريع إلى الأقسام الرئيسية لمتجرك.",
    manageOrders: "إدارة الطلبات",
    manageProducts: "إدارة المنتجات",
    manageCategories: "إدارة الفئات",
    accountSettings: "إعدادات الحساب",
    statsFetchError: "فشل في جلب إحصائيات لوحة التحكم.",
    processing: "قيد المعالجة",
    paymentPending: "في انتظار الدفع",
    paid: "مدفوع",
    confirmed: "تم التأكيد",
    rejected: "مرفوض",
    delivered: "تم التوصيل",
  },

}


